[project]
name = "auth-service"
version = "0.1.0"
description = "Authentication Service"
requires-python = ">=3.13"
dependencies = [
    "Flask>=3.1.1",
    "pymongo>=4.13.2",
    "PyJWT>=2.10.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "mongomock>=4.1.2",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
]
