[tool.uv.workspace]
members = [
    "burguer-app/auth-service",
    "burguer-app/order-service",
    "burguer-app/product-service",
    "burguer-app/user-service",
]

[project]
name = "python-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
